// Define the full dictionary of stations grouped by line name
export const stationsByLine = {
    "Lakeshore West": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Exhibition", stationCode: "EX" },
      { stationName: "Mimico", stationCode: "MI" },
      { stationName: "Long Branch", stationCode: "LO" },
      { stationName: "Port Credit", stationCode: "PO" },
      { stationName: "Clarkson", stationCode: "CL" },
      { stationName: "Oakville", stationCode: "OA" },
      { stationName: "Bronte", stationCode: "BO" },
      { stationName: "Appleby", stationCode: "AP" },
      { stationName: "Burlington", stationCode: "BU" },
      { stationName: "Aldershot", stationCode: "AL" },
      { stationName: "Hamilton", stationCode: "HA" },
      { stationName: "West Harbour", stationCode: "WR" },
      { stationName: "St. Catharines", stationCode: "SCTH" },
      { stationName: "Niagara Falls", stationCode: "NI" },
    ],
    "Lakeshore East": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Danforth", stationCode: "DA" },
      { stationName: "Scarborough", stationCode: "SC" },
      { stationName: "Eglinton", stationCode: "EG" },
      { stationName: "Guildwood", stationCode: "GU" },
      { stationName: "Rouge Hill", stationCode: "RO" },
      { stationName: "Pickering", stationCode: "PIN" },
      { stationName: "Ajax", stationCode: "AJ" },
      { stationName: "Whitby", stationCode: "WH" },
      { stationName: "Oshawa", stationCode: "OS" },
    ],
    "Milton": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Kipling", stationCode: "KP" },
      { stationName: "Dixie", stationCode: "DI" },
      { stationName: "Cooksville", stationCode: "CO" },
      { stationName: "Erindale", stationCode: "ER" },
      { stationName: "Streetsville", stationCode: "SR" },
      { stationName: "Meadowvale", stationCode: "ME" },
      { stationName: "Lisgar", stationCode: "LS" },
      { stationName: "Milton", stationCode: "ML" },
    ],
    "Kitchener": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Bloor", stationCode: "BL" },
      { stationName: "Weston", stationCode: "WE" },
      { stationName: "Etobicoke North", stationCode: "ET" },
      { stationName: "Malton", stationCode: "MA" },
      { stationName: "Bramalea", stationCode: "BE" },
      { stationName: "Brampton", stationCode: "BR" },
      { stationName: "Mount Pleasant", stationCode: "MO" },
      { stationName: "Georgetown", stationCode: "GE" },
      { stationName: "Acton", stationCode: "AC" },
      { stationName: "Guelph", stationCode: "GL" },
      { stationName: "Kitchener", stationCode: "KI" },
    ],
    "Barrie": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Downsview Park", stationCode: "DW" },
      { stationName: "Rutherford", stationCode: "RU" },
      { stationName: "Maple", stationCode: "MP" },
      { stationName: "King City", stationCode: "KC" },
      { stationName: "Aurora", stationCode: "AU" },
      { stationName: "Newmarket", stationCode: "NE" },
      { stationName: "East Gwillimbury", stationCode: "EA" },
      { stationName: "Bradford", stationCode: "BD" },
      { stationName: "Barrie South", stationCode: "BA" },
      { stationName: "Allandale Waterfront", stationCode: "AD" },
    ],
    "Richmond Hill": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Oriole", stationCode: "OR" },
      { stationName: "Old Cummer", stationCode: "OL" },
      { stationName: "Langstaff", stationCode: "LA" },
      { stationName: "Richmond Hill", stationCode: "RI" },
      { stationName: "Gormley", stationCode: "GO" },
      { stationName: "Bloomington", stationCode: "BM" },
    ],
    "Stouffville": [
      { stationName: "Union Station", stationCode: "UN" },
      { stationName: "Kennedy", stationCode: "KE" },
      { stationName: "Agincourt", stationCode: "AG" },
      { stationName: "Milliken", stationCode: "MK" },
      { stationName: "Unionville", stationCode: "UI" },
      { stationName: "Centennial", stationCode: "CE" },
      { stationName: "Markham", stationCode: "MR" },
      { stationName: "Mount Joy", stationCode: "MJ" },
      { stationName: "Stouffville", stationCode: "ST" },
      { stationName: "Old Elm", stationCode: "LI" },
    ],
  };
  
  